SET TIMEZONE TO +7;

INSERT INTO account.promotion(code,
                              journal,
                              ccy,
                              game_category,
                              auto_apply,
                              adjust_type,
                              bonus_value,
                              turnover_factor,
                              description,
                              max_apply_time,
                              start_time,
                              status)
VALUES ('DEPOSIT_50',
        'DEPOSIT',
        'VND',
        'LOTTERY',
        TRUE,
        'PERCENT',
        50,
        10,
        'Tặng 50% giá trị nạp tiền lần đầu',
        1,
        current_timestamp,
        'APPLYING'),
       ('BET_100K',
        'BET',
        'VND',
        'LOTTERY',
        TRUE,
        'AMT',
        100000,
        20,
        'Tặng 100k cho lần cược lần đầu',
        1,
        current_timestamp,
        'APPLYING');