apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: letsencrypt
spec:
 acme:
   email: arch18.3bb@gmail.com
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: letsencrypt
   providers:
    - name: digitalocean-dns
      digitalocean:
        tokenSecretRef:
          name: digitalocean-dns
          key: access-token
